version: "3.8"

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  app-server:
    build:
      context: .
      dockerfile: dockerfiles/appserver/Dockerfile
    container_name: app-server
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    volumes:
      - ./databases:/usr/src/app/databases
    depends_on:
      - securag-server

  securag-server:
    build:
      context: .
      dockerfile: dockerfiles/securag/Dockerfile
    container_name: securag-server
    ports:
      - "5000:5000"
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
      - sample.env
    volumes:
      - ./databases:/usr/src/app/databases

  ui:
    build:
      context: .
      dockerfile: dockerfiles/frontend/Dockerfile   # create this Dockerfile for frontend
    container_name: ui
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true   # helps hot reload in Docker
    env_file:
      - .env
    stdin_open: true
    tty: true
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  ollama:
  databases:
