name: Publish to PyPI

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  deploy:
    name: Build and Publish to PyPI
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: python/securag

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Build Tools
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build Package
        run: python -m build --outdir ../../dist

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages_dir: dist
